/*
 * file:   batchDistance.cpp
 * author: A trusty code generator
 * date:   Tue, 28 Feb 2017 10:45:57
 *
 * This file was autogenerated, do not modify.
 * See LICENSE for full modification and redistribution details.
 * Copyright 2017 The OpenCV Foundation
 */
#include <string>
#include <vector>
#include <cassert>
#include <exception>
#include <opencv2/matlab/bridge.hpp>
#include <opencv2/core.hpp>
using namespace cv;
using namespace matlab;
using namespace bridge;

/*
 * batchDistance
 * void batchDistance(Mat src1, Mat src2, Mat dist, int dtype, Mat nidx, int normType=NORM_L2, int K=0, Mat mask=Mat(), int update=0, bool crosscheck=false);
 * Gateway routine
 *   nlhs - number of return arguments
 *   plhs - pointers to return arguments
 *   nrhs - number of input arguments
 *   prhs - pointers to input arguments
 */
void mexFunction(int nlhs, mxArray* plhs[],
                 int nrhs, const mxArray* prhs[]) {

  // parse the inputs
  ArgumentParser parser("batchDistance");
  parser.addVariant("batchDistance", 3, 5, "normType", "K", "mask", "update", "crosscheck");
  MxArrayVector sorted = parser.parse(MxArrayVector(prhs, prhs+nrhs));

  // setup
  BridgeVector inputs(sorted.begin(), sorted.end());
  BridgeVector outputs(2);

  
  // unpack the arguments
  Mat src1 = inputs[0].toMat();
  Mat src2 = inputs[1].toMat();
  int dtype = inputs[2].toInt();
  int normType = inputs[3].empty() ? (int) NORM_L2 : inputs[3].toInt();
  int K = inputs[4].empty() ? (int) 0 : inputs[4].toInt();
  Mat mask = inputs[5].empty() ? (Mat) Mat() : inputs[5].toMat();
  int update = inputs[6].empty() ? (int) 0 : inputs[6].toInt();
  bool crosscheck = inputs[7].empty() ? (bool) false : inputs[7].toBool();
  Mat dist;
  Mat nidx;

  // call the opencv function
  // [out =] namespace.fun(src1, ..., srcn, dst1, ..., dstn, opt1, ..., optn);
  try {
    cv::batchDistance(src1, src2, dist, dtype, nidx, normType, K, mask, update, crosscheck);
  } catch(cv::Exception& e) {
    error(std::string("cv::exception caught: ").append(e.what()).c_str());
  } catch(std::exception& e) {
    error(std::string("std::exception caught: ").append(e.what()).c_str());
  } catch(...) {
    error("Uncaught exception occurred in batchDistance");
  }
  
  // assign the outputs into the bridge
  outputs[0] = dist;
  outputs[1] = nidx;


  // push the outputs back to matlab
  for (size_t n = 0; n < static_cast<size_t>(std::max(nlhs,1)); ++n) {
    plhs[n] = outputs[n].toMxArray().releaseOwnership();
  }
}