/*
 * file:   calcHist.cpp
 * author: A trusty code generator
 * date:   Tue, 28 Feb 2017 10:45:57
 *
 * This file was autogenerated, do not modify.
 * See LICENSE for full modification and redistribution details.
 * Copyright 2017 The OpenCV Foundation
 */
#include <string>
#include <vector>
#include <cassert>
#include <exception>
#include <opencv2/matlab/bridge.hpp>
#include <opencv2/imgproc.hpp>
using namespace cv;
using namespace matlab;
using namespace bridge;

/*
 * calcHist
 * void calcHist(vector_Mat images, vector_int channels, Mat mask, Mat hist, vector_int histSize, vector_float ranges, bool accumulate=false);
 * Gateway routine
 *   nlhs - number of return arguments
 *   plhs - pointers to return arguments
 *   nrhs - number of input arguments
 *   prhs - pointers to input arguments
 */
void mexFunction(int nlhs, mxArray* plhs[],
                 int nrhs, const mxArray* prhs[]) {

  // parse the inputs
  ArgumentParser parser("calcHist");
  parser.addVariant("calcHist", 5, 1, "accumulate");
  MxArrayVector sorted = parser.parse(MxArrayVector(prhs, prhs+nrhs));

  // setup
  BridgeVector inputs(sorted.begin(), sorted.end());
  BridgeVector outputs(1);

  
  // unpack the arguments
  vector_Mat images = inputs[0].toVectorMat();
  vector_int channels = inputs[1].toVectorInt();
  Mat mask = inputs[2].toMat();
  vector_int histSize = inputs[3].toVectorInt();
  vector_float ranges = inputs[4].toVectorFloat();
  bool accumulate = inputs[5].empty() ? (bool) false : inputs[5].toBool();
  Mat hist;

  // call the opencv function
  // [out =] namespace.fun(src1, ..., srcn, dst1, ..., dstn, opt1, ..., optn);
  try {
    cv::calcHist(images, channels, mask, hist, histSize, ranges, accumulate);
  } catch(cv::Exception& e) {
    error(std::string("cv::exception caught: ").append(e.what()).c_str());
  } catch(std::exception& e) {
    error(std::string("std::exception caught: ").append(e.what()).c_str());
  } catch(...) {
    error("Uncaught exception occurred in calcHist");
  }
  
  // assign the outputs into the bridge
  outputs[0] = hist;


  // push the outputs back to matlab
  for (size_t n = 0; n < static_cast<size_t>(std::max(nlhs,1)); ++n) {
    plhs[n] = outputs[n].toMxArray().releaseOwnership();
  }
}