/*
 * file:   drawMarker.cpp
 * author: A trusty code generator
 * date:   Tue, 28 Feb 2017 10:45:57
 *
 * This file was autogenerated, do not modify.
 * See LICENSE for full modification and redistribution details.
 * Copyright 2017 The OpenCV Foundation
 */
#include <string>
#include <vector>
#include <cassert>
#include <exception>
#include <opencv2/matlab/bridge.hpp>
#include <opencv2/imgproc.hpp>
using namespace cv;
using namespace matlab;
using namespace bridge;

/*
 * drawMarker
 * void drawMarker(Mat img, Point position, Scalar color, int markerType=MARKER_CROSS, int markerSize=20, int thickness=1, int line_type=8);
 * Gateway routine
 *   nlhs - number of return arguments
 *   plhs - pointers to return arguments
 *   nrhs - number of input arguments
 *   prhs - pointers to input arguments
 */
void mexFunction(int nlhs, mxArray* plhs[],
                 int nrhs, const mxArray* prhs[]) {

  // parse the inputs
  ArgumentParser parser("drawMarker");
  parser.addVariant("drawMarker", 3, 4, "markerType", "markerSize", "thickness", "line_type");
  MxArrayVector sorted = parser.parse(MxArrayVector(prhs, prhs+nrhs));

  // setup
  BridgeVector inputs(sorted.begin(), sorted.end());
  BridgeVector outputs(1);

  
  // unpack the arguments
  Mat img = inputs[0].toMat();
  Point position = inputs[1].toPoint();
  Scalar color = inputs[2].toScalar();
  int markerType = inputs[3].empty() ? (int) MARKER_CROSS : inputs[3].toInt();
  int markerSize = inputs[4].empty() ? (int) 20 : inputs[4].toInt();
  int thickness = inputs[5].empty() ? (int) 1 : inputs[5].toInt();
  int line_type = inputs[6].empty() ? (int) 8 : inputs[6].toInt();

  // call the opencv function
  // [out =] namespace.fun(src1, ..., srcn, dst1, ..., dstn, opt1, ..., optn);
  try {
    cv::drawMarker(img, position, color, markerType, markerSize, thickness, line_type);
  } catch(cv::Exception& e) {
    error(std::string("cv::exception caught: ").append(e.what()).c_str());
  } catch(std::exception& e) {
    error(std::string("std::exception caught: ").append(e.what()).c_str());
  } catch(...) {
    error("Uncaught exception occurred in drawMarker");
  }
  
  // assign the outputs into the bridge
  outputs[0] = img;


  // push the outputs back to matlab
  for (size_t n = 0; n < static_cast<size_t>(std::max(nlhs,1)); ++n) {
    plhs[n] = outputs[n].toMxArray().releaseOwnership();
  }
}