/*
 * file:   fastNlMeansDenoisingColoredMulti.cpp
 * author: A trusty code generator
 * date:   Tue, 28 Feb 2017 10:45:57
 *
 * This file was autogenerated, do not modify.
 * See LICENSE for full modification and redistribution details.
 * Copyright 2017 The OpenCV Foundation
 */
#include <string>
#include <vector>
#include <cassert>
#include <exception>
#include <opencv2/matlab/bridge.hpp>
#include <opencv2/photo.hpp>
using namespace cv;
using namespace matlab;
using namespace bridge;

/*
 * fastNlMeansDenoisingColoredMulti
 * void fastNlMeansDenoisingColoredMulti(vector_Mat srcImgs, Mat dst, int imgToDenoiseIndex, int temporalWindowSize, float h=3, float hColor=3, int templateWindowSize=7, int searchWindowSize=21);
 * Gateway routine
 *   nlhs - number of return arguments
 *   plhs - pointers to return arguments
 *   nrhs - number of input arguments
 *   prhs - pointers to input arguments
 */
void mexFunction(int nlhs, mxArray* plhs[],
                 int nrhs, const mxArray* prhs[]) {

  // parse the inputs
  ArgumentParser parser("fastNlMeansDenoisingColoredMulti");
  parser.addVariant("fastNlMeansDenoisingColoredMulti", 3, 4, "h", "hColor", "templateWindowSize", "searchWindowSize");
  MxArrayVector sorted = parser.parse(MxArrayVector(prhs, prhs+nrhs));

  // setup
  BridgeVector inputs(sorted.begin(), sorted.end());
  BridgeVector outputs(1);

  
  // unpack the arguments
  vector_Mat srcImgs = inputs[0].toVectorMat();
  int imgToDenoiseIndex = inputs[1].toInt();
  int temporalWindowSize = inputs[2].toInt();
  float h = inputs[3].empty() ? (float) 3 : inputs[3].toFloat();
  float hColor = inputs[4].empty() ? (float) 3 : inputs[4].toFloat();
  int templateWindowSize = inputs[5].empty() ? (int) 7 : inputs[5].toInt();
  int searchWindowSize = inputs[6].empty() ? (int) 21 : inputs[6].toInt();
  Mat dst;

  // call the opencv function
  // [out =] namespace.fun(src1, ..., srcn, dst1, ..., dstn, opt1, ..., optn);
  try {
    cv::fastNlMeansDenoisingColoredMulti(srcImgs, dst, imgToDenoiseIndex, temporalWindowSize, h, hColor, templateWindowSize, searchWindowSize);
  } catch(cv::Exception& e) {
    error(std::string("cv::exception caught: ").append(e.what()).c_str());
  } catch(std::exception& e) {
    error(std::string("std::exception caught: ").append(e.what()).c_str());
  } catch(...) {
    error("Uncaught exception occurred in fastNlMeansDenoisingColoredMulti");
  }
  
  // assign the outputs into the bridge
  outputs[0] = dst;


  // push the outputs back to matlab
  for (size_t n = 0; n < static_cast<size_t>(std::max(nlhs,1)); ++n) {
    plhs[n] = outputs[n].toMxArray().releaseOwnership();
  }
}