/*
 * file:   initWideAngleProjMap.cpp
 * author: A trusty code generator
 * date:   Tue, 28 Feb 2017 10:45:57
 *
 * This file was autogenerated, do not modify.
 * See LICENSE for full modification and redistribution details.
 * Copyright 2017 The OpenCV Foundation
 */
#include <string>
#include <vector>
#include <cassert>
#include <exception>
#include <opencv2/matlab/bridge.hpp>
#include <opencv2/imgproc.hpp>
using namespace cv;
using namespace matlab;
using namespace bridge;

/*
 * initWideAngleProjMap
 * float initWideAngleProjMap(Mat cameraMatrix, Mat distCoeffs, Size imageSize, int destImageWidth, int m1type, Mat map1, Mat map2, int projType=PROJ_SPHERICAL_EQRECT, double alpha=0);
 * Gateway routine
 *   nlhs - number of return arguments
 *   plhs - pointers to return arguments
 *   nrhs - number of input arguments
 *   prhs - pointers to input arguments
 */
void mexFunction(int nlhs, mxArray* plhs[],
                 int nrhs, const mxArray* prhs[]) {

  // parse the inputs
  ArgumentParser parser("initWideAngleProjMap");
  parser.addVariant("initWideAngleProjMap", 5, 2, "projType", "alpha");
  MxArrayVector sorted = parser.parse(MxArrayVector(prhs, prhs+nrhs));

  // setup
  BridgeVector inputs(sorted.begin(), sorted.end());
  BridgeVector outputs(3);

  
  // unpack the arguments
  Mat cameraMatrix = inputs[0].toMat();
  Mat distCoeffs = inputs[1].toMat();
  Size imageSize = inputs[2].toSize();
  int destImageWidth = inputs[3].toInt();
  int m1type = inputs[4].toInt();
  int projType = inputs[5].empty() ? (int) PROJ_SPHERICAL_EQRECT : inputs[5].toInt();
  double alpha = inputs[6].empty() ? (double) 0 : inputs[6].toDouble();
  Mat map1;
  Mat map2;
  float retval;

  // call the opencv function
  // [out =] namespace.fun(src1, ..., srcn, dst1, ..., dstn, opt1, ..., optn);
  try {
    retval = cv::initWideAngleProjMap(cameraMatrix, distCoeffs, imageSize, destImageWidth, m1type, map1, map2, projType, alpha);
  } catch(cv::Exception& e) {
    error(std::string("cv::exception caught: ").append(e.what()).c_str());
  } catch(std::exception& e) {
    error(std::string("std::exception caught: ").append(e.what()).c_str());
  } catch(...) {
    error("Uncaught exception occurred in initWideAngleProjMap");
  }
  
  // assign the outputs into the bridge
  outputs[0] = retval;
  outputs[1] = map1;
  outputs[2] = map2;


  // push the outputs back to matlab
  for (size_t n = 0; n < static_cast<size_t>(std::max(nlhs,1)); ++n) {
    plhs[n] = outputs[n].toMxArray().releaseOwnership();
  }
}