/*
 * file:   integral.cpp
 * author: A trusty code generator
 * date:   Tue, 28 Feb 2017 10:45:57
 *
 * This file was autogenerated, do not modify.
 * See LICENSE for full modification and redistribution details.
 * Copyright 2017 The OpenCV Foundation
 */
#include <string>
#include <vector>
#include <cassert>
#include <exception>
#include <opencv2/matlab/bridge.hpp>
#include <opencv2/imgproc.hpp>
using namespace cv;
using namespace matlab;
using namespace bridge;

/*
 * integral
 * void integral(Mat src, Mat sum, Mat sqsum, Mat tilted, int sdepth=-1, int sqdepth=-1);
 * Gateway routine
 *   nlhs - number of return arguments
 *   plhs - pointers to return arguments
 *   nrhs - number of input arguments
 *   prhs - pointers to input arguments
 */
void mexFunction(int nlhs, mxArray* plhs[],
                 int nrhs, const mxArray* prhs[]) {

  // parse the inputs
  ArgumentParser parser("integral");
  parser.addVariant("integral", 1, 2, "sdepth", "sqdepth");
  MxArrayVector sorted = parser.parse(MxArrayVector(prhs, prhs+nrhs));

  // setup
  BridgeVector inputs(sorted.begin(), sorted.end());
  BridgeVector outputs(3);

  
  // unpack the arguments
  Mat src = inputs[0].toMat();
  int sdepth = inputs[1].empty() ? (int) -1 : inputs[1].toInt();
  int sqdepth = inputs[2].empty() ? (int) -1 : inputs[2].toInt();
  Mat sum;
  Mat sqsum;
  Mat tilted;

  // call the opencv function
  // [out =] namespace.fun(src1, ..., srcn, dst1, ..., dstn, opt1, ..., optn);
  try {
    cv::integral(src, sum, sqsum, tilted, sdepth, sqdepth);
  } catch(cv::Exception& e) {
    error(std::string("cv::exception caught: ").append(e.what()).c_str());
  } catch(std::exception& e) {
    error(std::string("std::exception caught: ").append(e.what()).c_str());
  } catch(...) {
    error("Uncaught exception occurred in integral");
  }
  
  // assign the outputs into the bridge
  outputs[0] = sum;
  outputs[1] = sqsum;
  outputs[2] = tilted;


  // push the outputs back to matlab
  for (size_t n = 0; n < static_cast<size_t>(std::max(nlhs,1)); ++n) {
    plhs[n] = outputs[n].toMxArray().releaseOwnership();
  }
}