/*
 * file:   line.cpp
 * author: A trusty code generator
 * date:   Tue, 28 Feb 2017 10:45:57
 *
 * This file was autogenerated, do not modify.
 * See LICENSE for full modification and redistribution details.
 * Copyright 2017 The OpenCV Foundation
 */
#include <string>
#include <vector>
#include <cassert>
#include <exception>
#include <opencv2/matlab/bridge.hpp>
#include <opencv2/imgproc.hpp>
using namespace cv;
using namespace matlab;
using namespace bridge;

/*
 * line
 * void line(Mat img, Point pt1, Point pt2, Scalar color, int thickness=1, int lineType=LINE_8, int shift=0);
 * Gateway routine
 *   nlhs - number of return arguments
 *   plhs - pointers to return arguments
 *   nrhs - number of input arguments
 *   prhs - pointers to input arguments
 */
void mexFunction(int nlhs, mxArray* plhs[],
                 int nrhs, const mxArray* prhs[]) {

  // parse the inputs
  ArgumentParser parser("line");
  parser.addVariant("line", 4, 3, "thickness", "lineType", "shift");
  MxArrayVector sorted = parser.parse(MxArrayVector(prhs, prhs+nrhs));

  // setup
  BridgeVector inputs(sorted.begin(), sorted.end());
  BridgeVector outputs(1);

  
  // unpack the arguments
  Mat img = inputs[0].toMat();
  Point pt1 = inputs[1].toPoint();
  Point pt2 = inputs[2].toPoint();
  Scalar color = inputs[3].toScalar();
  int thickness = inputs[4].empty() ? (int) 1 : inputs[4].toInt();
  int lineType = inputs[5].empty() ? (int) LINE_8 : inputs[5].toInt();
  int shift = inputs[6].empty() ? (int) 0 : inputs[6].toInt();

  // call the opencv function
  // [out =] namespace.fun(src1, ..., srcn, dst1, ..., dstn, opt1, ..., optn);
  try {
    cv::line(img, pt1, pt2, color, thickness, lineType, shift);
  } catch(cv::Exception& e) {
    error(std::string("cv::exception caught: ").append(e.what()).c_str());
  } catch(std::exception& e) {
    error(std::string("std::exception caught: ").append(e.what()).c_str());
  } catch(...) {
    error("Uncaught exception occurred in line");
  }
  
  // assign the outputs into the bridge
  outputs[0] = img;


  // push the outputs back to matlab
  for (size_t n = 0; n < static_cast<size_t>(std::max(nlhs,1)); ++n) {
    plhs[n] = outputs[n].toMxArray().releaseOwnership();
  }
}