/*
 * file:   resizeWindow.cpp
 * author: A trusty code generator
 * date:   Tue, 28 Feb 2017 10:45:57
 *
 * This file was autogenerated, do not modify.
 * See LICENSE for full modification and redistribution details.
 * Copyright 2017 The OpenCV Foundation
 */
#include <string>
#include <vector>
#include <cassert>
#include <exception>
#include <opencv2/matlab/bridge.hpp>
#include <opencv2/highgui.hpp>
using namespace cv;
using namespace matlab;
using namespace bridge;

/*
 * resizeWindow
 * void resizeWindow(String winname, int width, int height);
 * Gateway routine
 *   nlhs - number of return arguments
 *   plhs - pointers to return arguments
 *   nrhs - number of input arguments
 *   prhs - pointers to input arguments
 */
void mexFunction(int nlhs, mxArray**,
                 int nrhs, const mxArray* prhs[]) {

  // parse the inputs
  ArgumentParser parser("resizeWindow");
  parser.addVariant("resizeWindow", 3, 0);
  MxArrayVector sorted = parser.parse(MxArrayVector(prhs, prhs+nrhs));

  // setup
  BridgeVector inputs(sorted.begin(), sorted.end());

  
  // unpack the arguments
  String winname = inputs[0].toString();
  int width = inputs[1].toInt();
  int height = inputs[2].toInt();

  // call the opencv function
  // [out =] namespace.fun(src1, ..., srcn, dst1, ..., dstn, opt1, ..., optn);
  try {
    cv::resizeWindow(winname, width, height);
  } catch(cv::Exception& e) {
    error(std::string("cv::exception caught: ").append(e.what()).c_str());
  } catch(std::exception& e) {
    error(std::string("std::exception caught: ").append(e.what()).c_str());
  } catch(...) {
    error("Uncaught exception occurred in resizeWindow");
  }
  


}