/*
 * file:   solvePnPRansac.cpp
 * author: A trusty code generator
 * date:   Tue, 28 Feb 2017 10:45:57
 *
 * This file was autogenerated, do not modify.
 * See LICENSE for full modification and redistribution details.
 * Copyright 2017 The OpenCV Foundation
 */
#include <string>
#include <vector>
#include <cassert>
#include <exception>
#include <opencv2/matlab/bridge.hpp>
#include <opencv2/calib3d.hpp>
using namespace cv;
using namespace matlab;
using namespace bridge;

/*
 * solvePnPRansac
 * bool solvePnPRansac(Mat objectPoints, Mat imagePoints, Mat cameraMatrix, Mat distCoeffs, Mat rvec, Mat tvec, bool useExtrinsicGuess=false, int iterationsCount=100, float reprojectionError=8.0, double confidence=0.99, Mat inliers=Mat(), int flags=SOLVEPNP_ITERATIVE);
 * Gateway routine
 *   nlhs - number of return arguments
 *   plhs - pointers to return arguments
 *   nrhs - number of input arguments
 *   prhs - pointers to input arguments
 */
void mexFunction(int nlhs, mxArray* plhs[],
                 int nrhs, const mxArray* prhs[]) {

  // parse the inputs
  ArgumentParser parser("solvePnPRansac");
  parser.addVariant("solvePnPRansac", 4, 5, "useExtrinsicGuess", "iterationsCount", "reprojectionError", "confidence", "flags");
  MxArrayVector sorted = parser.parse(MxArrayVector(prhs, prhs+nrhs));

  // setup
  BridgeVector inputs(sorted.begin(), sorted.end());
  BridgeVector outputs(4);

  
  // unpack the arguments
  Mat objectPoints = inputs[0].toMat();
  Mat imagePoints = inputs[1].toMat();
  Mat cameraMatrix = inputs[2].toMat();
  Mat distCoeffs = inputs[3].toMat();
  bool useExtrinsicGuess = inputs[4].empty() ? (bool) false : inputs[4].toBool();
  int iterationsCount = inputs[5].empty() ? (int) 100 : inputs[5].toInt();
  float reprojectionError = inputs[6].empty() ? (float) 8.0 : inputs[6].toFloat();
  double confidence = inputs[7].empty() ? (double) 0.99 : inputs[7].toDouble();
  int flags = inputs[8].empty() ? (int) SOLVEPNP_ITERATIVE : inputs[8].toInt();
  Mat rvec;
  Mat tvec;
  Mat inliers;
  bool retval;

  // call the opencv function
  // [out =] namespace.fun(src1, ..., srcn, dst1, ..., dstn, opt1, ..., optn);
  try {
    retval = cv::solvePnPRansac(objectPoints, imagePoints, cameraMatrix, distCoeffs, rvec, tvec, useExtrinsicGuess, iterationsCount, reprojectionError, confidence, inliers, flags);
  } catch(cv::Exception& e) {
    error(std::string("cv::exception caught: ").append(e.what()).c_str());
  } catch(std::exception& e) {
    error(std::string("std::exception caught: ").append(e.what()).c_str());
  } catch(...) {
    error("Uncaught exception occurred in solvePnPRansac");
  }
  
  // assign the outputs into the bridge
  outputs[0] = retval;
  outputs[1] = rvec;
  outputs[2] = tvec;
  outputs[3] = inliers;


  // push the outputs back to matlab
  for (size_t n = 0; n < static_cast<size_t>(std::max(nlhs,1)); ++n) {
    plhs[n] = outputs[n].toMxArray().releaseOwnership();
  }
}