// This file is part of OpenCV project.
// It is subject to the license terms in the LICENSE file found in the top-level directory
// of this distribution and at http://opencv.org/license.html.
"Test_Caffe.memory_read",
"Test_Caffe.read_gtsrb",
"Test_Caffe.read_googlenet",
"Test_Caffe.multiple_inputs",
"Test_Caffe.shared_weights",
"Reproducibility_SSD.Accuracy",           // ONNX parse failure: Unsupported 'LpNormalization' op.
"Reproducibility_MobileNet_SSD.Accuracy", // ONNX import failure: Unsupported 'Graph' attribute in dynamic loops.
"Test_Caffe_layers.Softmax",
"Test_Caffe_layers.LRN",
"Test_Caffe_layers.Convolution",
"Test_Caffe_layers.DeConvolution",
"Test_Caffe_layers.InnerProduct",
"Test_Caffe_layers.Pooling_max",
"Test_Caffe_layers.Pooling_ave",
"Test_Caffe_layers.MVN",
"Test_Caffe_layers.BatchNorm",
"Test_Caffe_layers.ReLU",
"Test_Caffe_layers.Dropout",
"Test_Caffe_layers.Concat",
"Test_Caffe_layers.Fused_Concat",
"Test_Caffe_layers.Eltwise",
"Test_Caffe_layers.PReLU",
"Test_Caffe_layers.layer_prelu_fc",
"Test_Caffe_layers.Reshape_Split_Slice",
"Test_Caffe_layers.Conv_Elu",
"Test_Caffe_layers.Accum",
"Test_Caffe_layers.DataAugmentation",
"Test_Caffe_layers.Resample",
"Test_Caffe_layers.Correlation",
"Test_Caffe_layers.Convolution2Inputs",
"Test_Caffe_layers.ROIPooling_Accuracy",
"Test_Caffe_layers.FasterRCNN_Proposal",
"Test_Caffe_layers.FlowWarp",
"Test_Caffe_layers.ChannelNorm",
"Test_Caffe_layers.PriorBox_repeated",
"Test_Caffe_layers.Interp",
"Test_Caffe_nets.Axpy",
"Test_Caffe_nets.FasterRCNN_vgg16",
"Test_Caffe_nets.FasterRCNN_zf",
"Test_Caffe_nets.RFCN",
"Test_Caffe_nets.Colorization",           // ENGINE_NEW mismanages 'pts_in_hull' blob injections and layer fusions.
"Test_ONNX_layers.Deconvolution3D",
"Test_ONNX_layers.Deconvolution3D_bias",
"Test_ONNX_layers.Deconvolution3D_pad",
"Test_ONNX_layers.Deconvolution3D_adjpad",
"Test_ONNX_layers.Split_sizes_0d",
"Test_ONNX_layers.LSTM",
"Test_ONNX_layers.LSTM_bidirectional",
"Test_ONNX_layers.LSTM_layout_seq",
"Test_ONNX_layers.LSTM_layout_batch"
