function mex(varargin)
%CV.MEX compile MEX-function with OpenCV linkages
%
%   Usage:
%       CV.MEX [options ...] file [file file ...]
%
%   Description:
%       CV.MEX compiles one or more C/C++ source files into a shared-library
%       called a mex-file. This function is equivalent to the builtin MEX
%       routine, with the notable exception that it automatically resolves
%       OpenCV includes, and links in the OpenCV libraries where appropriate.
%       It also forwards the flags used to build OpenCV, so architecture-
%       specific optimizations can be used.
%
%       CV.MEX is designed to be used in situations where the source(s) you
%       are compiling contain OpenCV definitions. In such cases, it streamlines
%       the finding and including of appropriate OpenCV libraries.
%
%   See also: mex
%
%   Copyright 2017 The OpenCV Foundation
%

  % forward the OpenCV build flags (C++ only)
  EXTRA_FLAGS  = ['"CXXFLAGS="\$CXXFLAGS '...
                  '-fsigned-char -W -Wall -Werror=return-type -Werror=non-'...
                  'virtual-dtor -Werror=address -Werror=sequence-point -Wformat'...
                  '-Werror=format-security -Wmissing-declarations -Wmissing-'...
                  'prototypes -Wstrict-prototypes -Wundef -Winit-self'...
                  '-Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-'...
                  'delete-non-virtual-dtor -Wno-unnamed-type-template-args'...
                  '-Wno-comment -fdiagnostics-show-option -Wno-long-long'...
                  '-Qunused-arguments -Wno-semicolon-before-method-body -fno-'...
                  'omit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3'...
                  '-mno-sse4.1 -mno-sse4.2""'];

  % add the OpenCV include dirs
  INCLUDE_DIRS = {'-I/Users/chihiro/Programs/opencv/opencv/release',...
                  '-I/Users/chihiro/Programs/opencv/opencv_contrib/modules/matlab/include',...
                  '-I/Users/chihiro/Programs/opencv/opencv_contrib/modules/dnn/include',...
                  '-I/Users/chihiro/Programs/opencv/opencv/modules/core/include',...
                  '-I/Users/chihiro/Programs/opencv/opencv/modules/imgproc/include',...
                  '-I/Users/chihiro/Programs/opencv/opencv/modules/ml/include',...
                  '-I/Users/chihiro/Programs/opencv/opencv/modules/imgcodecs/include',...
                  '-I/Users/chihiro/Programs/opencv/opencv/modules/videoio/include',...
                  '-I/Users/chihiro/Programs/opencv/opencv/modules/highgui/include',...
                  '-I/Users/chihiro/Programs/opencv/opencv/modules/objdetect/include',...
                  '-I/Users/chihiro/Programs/opencv/opencv/modules/flann/include',...
                  '-I/Users/chihiro/Programs/opencv/opencv/modules/features2d/include',...
                  '-I/Users/chihiro/Programs/opencv/opencv/modules/photo/include',...
                  '-I/Users/chihiro/Programs/opencv/opencv/modules/video/include',...
                  '-I/Users/chihiro/Programs/opencv/opencv/modules/videostab/include',...
                  '-I/Users/chihiro/Programs/opencv/opencv/modules/calib3d/include',...
                  '-I/Users/chihiro/Programs/opencv/opencv/modules/stitching/include',...
                  '-I/Users/chihiro/Programs/opencv/opencv/modules/superres/include',...
                  '-I/Users/chihiro/Programs/opencv/opencv_contrib/modules/xfeatures2d/include'};

  % add the lib dir (singular in both build tree and install tree)
  LIB_DIR      = '-L/Users/chihiro/Programs/opencv/opencv/release/lib';

  % add the OpenCV libs. Only the used libs will actually be linked
  LIBS         = {'-lopencv_dnn', '-lopencv_core', '-lopencv_imgproc',...
                  '-lopencv_ml', '-lopencv_imgcodecs', '-lopencv_videoio',...
                  '-lopencv_highgui', '-lopencv_objdetect', '-lopencv_flann',...
                  '-lopencv_features2d', '-lopencv_photo', '-lopencv_video',...
                  '-lopencv_videostab', '-lopencv_calib3d',...
                  '-lopencv_stitching', '-lopencv_superres',...
                  '-lopencv_xfeatures2d'};

  % add the mex opts (usually at least -largeArrayDims)
  OPTS         = {'-largeArrayDims'};

  % merge all of the default options (EXTRA_FLAGS, LIBS, etc) and the options
  % and files passed by the user (varargin) into a single cell array
  merged       = [ {EXTRA_FLAGS}, INCLUDE_DIRS, {LIB_DIR}, LIBS, OPTS, varargin ];

  % expand the merged argument list into the builtin mex utility
  mex(merged{:});
end