# Install script for directory: /home/boney/opencvprog/opencv-source/modules

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/boney/opencvprog/opencv-source/modules/calib3d/.calib3d/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/core/.core/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/cudaarithm/.cudaarithm/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/cudabgsegm/.cudabgsegm/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/cudacodec/.cudacodec/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/cudafeatures2d/.cudafeatures2d/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/cudafilters/.cudafilters/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/cudaimgproc/.cudaimgproc/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/cudalegacy/.cudalegacy/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/cudaobjdetect/.cudaobjdetect/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/cudaoptflow/.cudaoptflow/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/cudastereo/.cudastereo/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/cudawarping/.cudawarping/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/cudev/.cudev/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/features2d/.features2d/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/flann/.flann/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/highgui/.highgui/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/imgcodecs/.imgcodecs/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/imgproc/.imgproc/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/java/.java/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/ml/.ml/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/objdetect/.objdetect/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/photo/.photo/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/python/.python/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/shape/.shape/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/stitching/.stitching/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/superres/.superres/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/ts/.ts/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/video/.video/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/videoio/.videoio/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/videostab/.videostab/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/viz/.viz/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/world/.world/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/core/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/flann/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/imgproc/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/ml/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/photo/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/video/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/viz/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/imgcodecs/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/shape/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/videoio/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/highgui/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/objdetect/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/superres/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/ts/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/features2d/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/calib3d/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/stitching/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/videostab/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/python2/cmake_install.cmake")
  include("/home/boney/opencvprog/opencv-source/modules/python3/cmake_install.cmake")

endif()

