set(CTEST_PROJECT_NAME "OpenCV_3")
set(CTEST_NIGHTLY_START_TIME "01:00:00 UTC")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "localhost")
set(CTEST_DROP_LOCATION "/CDash/submit.php?project=OpenCV_3")
set(CTEST_DROP_SITE_CDASH TRUE)
