tracker3D: object_tracker.cpp tracker3D.cpp tracker_calibration.cpp tracker_calibration.h tracker3D.h object_tracker.h
	g++ -o tracker3D -g object_tracker.cpp tracker3D.cpp tracker_calibration.cpp -lml -lcv -lcxcore -lcvaux -lhighgui
