#ifdef HAVE_OPENCV_FEATURES
typedef SimpleBlobDetector::Params SimpleBlobDetector_Params;
typedef FastFeatureDetector::DetectorType FastFeatureDetector_DetectorType;
typedef DescriptorMatcher::MatcherType DescriptorMatcher_MatcherType;
typedef ORB::ScoreType ORB_ScoreType;
#endif