#ifndef CAMERA_PROPERTIES_H
#define CAMERA_PROPERTIES_H

enum {
    ANDROID_CAMERA_PROPERTY_FRAMEWIDTH = 0,
    ANDROID_CAMERA_PROPERTY_FRAMEHEIGHT = 1,
    ANDROID_CAMERA_PROPERTY_SUPPORTED_PREVIEW_SIZES_STRING = 2
};

#endif // CAMERA_PROPERTIES_H
