/*
 * file:   BOWImgDescriptorExtractorBridge.cpp
 * author: A trusty code generator
 * date:   Tue, 28 Feb 2017 10:45:57
 *
 * This file was autogenerated, do not modify.
 * See LICENSE for full modification and redistribution details.
 * Copyright 2017 The OpenCV Foundation
 */
#include <mex.h>
#include <vector>
#include <string>
#include <opencv2/matlab/map.hpp>
#include <opencv2/matlab/bridge.hpp>
#include <opencv2/core.hpp>
using namespace cv;
using namespace matlab;
using namespace bridge;

namespace {

typedef std::vector<Bridge> (*)(BOWImgDescriptorExtractor&, const std::vector<Bridge>&) MethodSignature;


// wrapper for BOWImgDescriptorExtractor() constructor
BOWImgDescriptorExtractor BOWImgDescriptorExtractor(const std::vector<Bridge>& inputs) {
  
  // unpack the arguments
  Ptr_DescriptorExtractor dextractor = inputs[0].toPtrDescriptorExtractor();
  Ptr_DescriptorMatcher dmatcher = inputs[1].toPtrDescriptorMatcher();

  BOWImgDescriptorExtractor obj = cv::BOWImgDescriptorExtractor(dextractor, dmatcher);
  return obj;
}

// wrapper for setVocabulary() method
std::vector<Bridge> setVocabulary(BOWImgDescriptorExtractor& inst, const std::vector<Bridge>& inputs) {
  std::vector<Bridge> outputs;
  
  // unpack the arguments
  Mat vocabulary = inputs[0].toMat();

  // call the opencv function
  // [out =] namespace.fun(src1, ..., srcn, dst1, ..., dstn, opt1, ..., optn);
  try {
    inst.setVocabulary(vocabulary);
  } catch(cv::Exception& e) {
    error(std::string("cv::exception caught: ").append(e.what()).c_str());
  } catch(std::exception& e) {
    error(std::string("std::exception caught: ").append(e.what()).c_str());
  } catch(...) {
    error("Uncaught exception occurred in setVocabulary");
  }
  

  return outputs;
}

// wrapper for getVocabulary() method
std::vector<Bridge> getVocabulary(BOWImgDescriptorExtractor& inst, const std::vector<Bridge>& inputs) {
  std::vector<Bridge> outputs(1);
  
  // unpack the arguments
  Mat retval;

  // call the opencv function
  // [out =] namespace.fun(src1, ..., srcn, dst1, ..., dstn, opt1, ..., optn);
  try {
    retval = inst.getVocabulary();
  } catch(cv::Exception& e) {
    error(std::string("cv::exception caught: ").append(e.what()).c_str());
  } catch(std::exception& e) {
    error(std::string("std::exception caught: ").append(e.what()).c_str());
  } catch(...) {
    error("Uncaught exception occurred in getVocabulary");
  }
  
  // assign the outputs into the bridge
  outputs[0] = retval;

  return outputs;
}

// wrapper for compute2() method
std::vector<Bridge> compute2(BOWImgDescriptorExtractor& inst, const std::vector<Bridge>& inputs) {
  std::vector<Bridge> outputs(1);
  
  // unpack the arguments
  Mat image = inputs[0].toMat();
  vector_KeyPoint keypoints = inputs[1].toVectorKeyPoint();
  Mat imgDescriptor;

  // call the opencv function
  // [out =] namespace.fun(src1, ..., srcn, dst1, ..., dstn, opt1, ..., optn);
  try {
    inst.compute2(image, keypoints, imgDescriptor);
  } catch(cv::Exception& e) {
    error(std::string("cv::exception caught: ").append(e.what()).c_str());
  } catch(std::exception& e) {
    error(std::string("std::exception caught: ").append(e.what()).c_str());
  } catch(...) {
    error("Uncaught exception occurred in compute2");
  }
  
  // assign the outputs into the bridge
  outputs[0] = imgDescriptor;

  return outputs;
}

// wrapper for descriptorSize() method
std::vector<Bridge> descriptorSize(BOWImgDescriptorExtractor& inst, const std::vector<Bridge>& inputs) {
  std::vector<Bridge> outputs(1);
  
  // unpack the arguments
  int retval;

  // call the opencv function
  // [out =] namespace.fun(src1, ..., srcn, dst1, ..., dstn, opt1, ..., optn);
  try {
    retval = inst.descriptorSize();
  } catch(cv::Exception& e) {
    error(std::string("cv::exception caught: ").append(e.what()).c_str());
  } catch(std::exception& e) {
    error(std::string("std::exception caught: ").append(e.what()).c_str());
  } catch(...) {
    error("Uncaught exception occurred in descriptorSize");
  }
  
  // assign the outputs into the bridge
  outputs[0] = retval;

  return outputs;
}

// wrapper for descriptorType() method
std::vector<Bridge> descriptorType(BOWImgDescriptorExtractor& inst, const std::vector<Bridge>& inputs) {
  std::vector<Bridge> outputs(1);
  
  // unpack the arguments
  int retval;

  // call the opencv function
  // [out =] namespace.fun(src1, ..., srcn, dst1, ..., dstn, opt1, ..., optn);
  try {
    retval = inst.descriptorType();
  } catch(cv::Exception& e) {
    error(std::string("cv::exception caught: ").append(e.what()).c_str());
  } catch(std::exception& e) {
    error(std::string("std::exception caught: ").append(e.what()).c_str());
  } catch(...) {
    error("Uncaught exception occurred in descriptorType");
  }
  
  // assign the outputs into the bridge
  outputs[0] = retval;

  return outputs;
}

Map<std::string, MethodSignature> createMethodMap() {
  Map<std::string, MethodSignature> m;
  m["BOWImgDescriptorExtractor"] = &BOWImgDescriptorExtractor;
  m["setVocabulary"] = &setVocabulary;
  m["getVocabulary"] = &getVocabulary;
  m["compute2"] = &compute2;
  m["descriptorSize"] = &descriptorSize;
  m["descriptorType"] = &descriptorType;

  return m;
}
static const Map<std::string, MethodSignature> methods = createMethodMap();

// map of created BOWImgDescriptorExtractor instances. Don't trust the user to keep them safe...
static Map<void *, BOWImgDescriptorExtractor> instances;

/*
 * BOWImgDescriptorExtractor
 * Gateway routine
 *   nlhs - number of return arguments
 *   plhs - pointers to return arguments
 *   nrhs - number of input arguments
 *   prhs - pointers to input arguments
 */
void mexFunction(int nlhs, mxArray* plhs[],
                 int nrhs, const mxArray* prhs[]) {

  // parse the inputs
  Bridge method_name(prhs[0]);

  Bridge handle(prhs[1]);
  std::vector<Bridge> brhs(prhs+2, prhs+nrhs);

  // retrieve the instance of interest
  try {
    BOWImgDescriptorExtractor& inst = instances.at(handle.address());
  } catch (const std::out_of_range& e) {
    mexErrMsgTxt("Invalid object instance provided");
  }

  // invoke the correct method on the data
  try {
    std::vector<Bridge> blhs = (*methods.at(method_name))(inst, brhs);
  } catch (const std::out_of_range& e) {
    mexErrMsgTxt("Unknown method specified");
  }



}

} // end namespace