set(CATALYST TRUE)
if(NOT FINISHED_INCLUDE_IMPORT)
    message(STATUS "Setting up Catalyst toolchain for IOS_ARCH='${IOS_ARCH}'")
    include(${CMAKE_CURRENT_LIST_DIR}/common-ios-toolchain.cmake)
    message(STATUS "Catalyst toolchain loaded")
endif()
# set(FINISHED_INCLUDE_IMPORT TRUE)
