/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_android_OpenCVLoader */

#ifndef _Included_org_opencv_android_OpenCVLoader
#define _Included_org_opencv_android_OpenCVLoader
#ifdef __cplusplus
extern "C" {
#endif
#undef org_opencv_android_OpenCVLoader_Success
#define org_opencv_android_OpenCVLoader_Success 0L
#undef org_opencv_android_OpenCVLoader_NoService
#define org_opencv_android_OpenCVLoader_NoService 1L
#undef org_opencv_android_OpenCVLoader_RestartRequired
#define org_opencv_android_OpenCVLoader_RestartRequired 2L
#undef org_opencv_android_OpenCVLoader_MarketError
#define org_opencv_android_OpenCVLoader_MarketError 3L
#undef org_opencv_android_OpenCVLoader_InitFailed
#define org_opencv_android_OpenCVLoader_InitFailed 255L
/*
 * Class:     org_opencv_android_OpenCVLoader
 * Method:    GetLibraryList
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opencv_android_StaticHelper_getLibraryList
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
