function(ocv_set_platform_flags VAR)
  cmake_parse_arguments(arg "APPEND" "" "" ${ARGN})
  if(ENABLE_RVV OR RISCV_RVV_SCALABLE)
    set(flags "-march=rv64gcv")
  else()
    set(flags "-march=rv64gc")
  endif()
  if(arg_APPEND)
    set(${VAR} "${${VAR}} ${flags}" PARENT_SCOPE)
  else()
    set(${VAR} "${flags}" PARENT_SCOPE)
  endif()
endfunction()
