/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.opencv.jni;

public class PtrMat {
  private long swigCPtr;
  protected boolean swigCMemOwn;
  public PtrMat(long cPtr, boolean cMemoryOwn) {
	swigCMemOwn = cMemoryOwn;
	swigCPtr = cPtr;
  }
  public static long getCPtr(PtrMat obj) {
	return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opencvJNI.delete_PtrMat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PtrMat() {
    this(opencvJNI.new_PtrMat__SWIG_0(), true);
  }

  public PtrMat(Mat _obj) {
    this(opencvJNI.new_PtrMat__SWIG_1(Mat.getCPtr(_obj), _obj), true);
  }

  public PtrMat(PtrMat ptr) {
    this(opencvJNI.new_PtrMat__SWIG_2(PtrMat.getCPtr(ptr), ptr), true);
  }

  public void addref() {
    opencvJNI.PtrMat_addref(swigCPtr, this);
  }

  public void release() {
    opencvJNI.PtrMat_release(swigCPtr, this);
  }

  public void delete_obj() {
    opencvJNI.PtrMat_delete_obj(swigCPtr, this);
  }

  public boolean empty() {
    return opencvJNI.PtrMat_empty(swigCPtr, this);
  }

  public Mat __deref__() {
    long cPtr = opencvJNI.PtrMat___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new Mat(cPtr, false);
  }

  public int getRows() {
    return opencvJNI.PtrMat_rows_get(swigCPtr, this);
  }

  public int getCols() {
    return opencvJNI.PtrMat_cols_get(swigCPtr, this);
  }

}
