#!/bin/bash

LANGUAGES="${LANGUAGES:=c cpp py}"

mkdir -p $LANGUAGES
tput clear
python latex.py ../online-opencv.tex $LANGUAGES || exit

for D in $LANGUAGES
do
  echo $D
  mkdir -p _build/latex/$D
  cp conf.py $D
  cp mymath.sty _build/latex/$D
  TEXINPUTS=$PWD: sphinx-build -w $D/sphinx.errors -D "lang=$D" -b latex -d _build/doctrees/$D $D _build/latex/$D
  (cd _build/latex/$D && rm *.aux *.toc *.log && pdflatex opencv.tex)
done
