#!/bin/bash

LANGUAGES="${LANGUAGES:=c cpp py}"

mkdir -p $LANGUAGES
tput clear
python latex.py ../online-opencv.tex $LANGUAGES || exit

for D in $LANGUAGES
do
  echo $D
  mkdir -p $D
  sed "s/%LANG%/$D/" conf.py > $D/conf.py
  TEXINPUTS=$PWD: sphinx-build -w $D/sphinx.errors -D "lang=$D" -b html -d _build/doctrees/$D $D _build/html/$D

  #Insert javascript links to load the Wiki in a frame
  for file in `ls _build/html/$D/*.html`
  do
    cat $file | sed "/Comments from the Wiki/s/href=\"\(.*\)\">id=0.\([0-9]*\) /href=\"javascript:void\(0\)\" onclick=\"insertIframe\('\2', '\1'\)\" id=\"\2\">/" > tmp.html
    mv 'tmp.html' "$file"
  done
done


