# --- obsensor ---
if(NOT HAVE_OBSENSOR)
  if(WIN32)
    check_include_file(mfapi.h HAVE_MFAPI)
    if(HAVE_MFAPI)
      set(HAVE_OBSENSOR TRUE)
      set(HAVE_OBSENSOR_MSMF TRUE)
      ocv_add_external_target(obsensor "" "" "HAVE_OBSENSOR;HAVE_OBSENSOR_MSMF")
    endif()
  elseif(UNIX)
    check_include_file(linux/videodev2.h HAVE_CAMV4L2)
    if(HAVE_CAMV4L2)
      set(HAVE_OBSENSOR TRUE)
      set(HAVE_OBSENSOR_V4L2 TRUE)
      ocv_add_external_target(obsensor "" "" "HAVE_OBSENSOR;HAVE_OBSENSOR_V4L2")
    endif()
  endif()
endif()
