name: PR:4.x

on:
  pull_request:
    branches:
      - 4.x

jobs:
  Linux:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-Linux.yaml@add-custom-action

  docs:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-4.x-docs.yaml@add-custom-action
